/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import CustomizeDlg from "./script/CustomizeDlg"
import GameUI from "./script/GameUI"
import ProgressView from "./script/ProgressView"
import SettingDlg from "./script/SettingDlg"
import WorldDlg from "./script/WorldDlg"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=960;
    static scaleMode:string="showall";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="GameScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/CustomizeDlg.ts",CustomizeDlg);
        reg("script/GameUI.ts",GameUI);
        reg("script/ProgressView.ts",ProgressView);
        reg("script/SettingDlg.ts",SettingDlg);
        reg("script/WorldDlg.ts",WorldDlg);
    }
}
GameConfig.init();